# Generated by Django 5.2.12 on 2026-04-01 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_sheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-sheet_date", "user_id"),
            },
        ),
        migrations.CreateModel(
            name="WorkSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Personal 1"),
                            (2, "Personal 2"),
                            (3, "Personal 3"),
                            (4, "Admin"),
                        ]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("personal", "Personal"), ("admin", "Admin")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("goal", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "daily_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_sessions",
                        to="core.dailysheet",
                    ),
                ),
            ],
            options={
                "ordering": ("daily_sheet_id", "slot"),
            },
        ),
        migrations.AddConstraint(
            model_name="dailysheet",
            constraint=models.UniqueConstraint(
                fields=("user", "sheet_date"), name="daily_sheet_unique_user_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="worksession",
            constraint=models.UniqueConstraint(
                fields=("daily_sheet", "slot"), name="work_session_unique_sheet_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="worksession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("slot__in", [1, 2, 3]), ("category", "personal")),
                    models.Q(("slot", 4), ("category", "admin")),
                    _connector="OR",
                ),
                name="work_session_slot_category_match",
            ),
        ),
    ]
