# Generated by Django 5.2.12 on 2026-04-02 22:18

import django.core.validators
from django.db import migrations, models


def backfill_work_session_timer_fields(apps, schema_editor):
    UserPreferences = apps.get_model("core", "UserPreferences")
    WorkSession = apps.get_model("core", "WorkSession")
    db_alias = schema_editor.connection.alias
    update_fields = [
        "duration_minutes",
        "started_at",
        "active_started_at",
        "elapsed_seconds",
        "completed_at",
        "skipped_at",
    ]
    batch_size = 500

    def process_session_batch(sessions):
        default_duration_by_user_id = dict(
            UserPreferences.objects.using(db_alias)
            .filter(user_id__in={session.daily_sheet.user_id for session in sessions})
            .values_list(
                "user_id",
                "default_session_duration_minutes",
            )
        )

        for session in sessions:
            session.duration_minutes = default_duration_by_user_id.get(
                session.daily_sheet.user_id,
                45,
            )

            if session.status == "active":
                if session.started_at is None:
                    session.started_at = session.updated_at
                session.active_started_at = session.started_at
                session.completed_at = None
                session.skipped_at = None
                session.elapsed_seconds = 0
            elif session.status == "completed":
                if session.started_at is None:
                    session.started_at = session.updated_at
                if session.completed_at is None:
                    session.completed_at = session.updated_at
                session.active_started_at = None
                session.skipped_at = None
                session.elapsed_seconds = max(
                    int((session.completed_at - session.started_at).total_seconds()),
                    0,
                )
            elif session.status == "skipped":
                session.started_at = None
                session.active_started_at = None
                session.completed_at = None
                if session.skipped_at is None:
                    session.skipped_at = session.updated_at
                session.elapsed_seconds = 0
            else:
                session.started_at = None
                session.active_started_at = None
                session.completed_at = None
                session.skipped_at = None
                session.elapsed_seconds = 0

        WorkSession.objects.using(db_alias).bulk_update(
            sessions,
            update_fields,
            batch_size=batch_size,
        )

    sessions_to_update = []

    for session in (
        WorkSession.objects.using(db_alias)
        .select_related("daily_sheet")
        .iterator(chunk_size=batch_size)
    ):
        sessions_to_update.append(session)
        if len(sessions_to_update) == batch_size:
            process_session_batch(sessions_to_update)
            sessions_to_update.clear()

    if sessions_to_update:
        process_session_batch(sessions_to_update)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_dailysheet_worksession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksession",
            name="active_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worksession",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(
                default=45, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="worksession",
            name="elapsed_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            backfill_work_session_timer_fields,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="worksession",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("skipped", "Skipped"),
                ],
                default="planned",
                max_length=16,
            ),
        ),
    ]
